baseurl = "https://brianrc.github.io/hugotest/"
title = "My New Awesome Site"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Brian Cruikshank"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "Brian Cruikshank"
  email = "brianrc6@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/humboldtux"
[[params.social]]
  title = "github"
  url = "https://github.com/humboldtux"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "about"
  weight = -110
  url = "/about/"
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
